USE [DS_HSDM_App_Dev]
GO

-- ===========================================
-- Create table Rptg.ED_Goals
-- ===========================================
IF EXISTS (SELECT TABLE_NAME 
	       FROM   INFORMATION_SCHEMA.TABLES
	       WHERE  TABLE_SCHEMA = N'Rptg' AND
	              TABLE_NAME = N'ED_Goals')
   DROP TABLE [Rptg].[ED_Goals]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[ED_Goals](
	[SVC_CDE] [VARCHAR](2) NULL,
	[GOAL_FISCAL_YR] [INT] NULL,
	[SERVICE_LINE] [VARCHAR](150) NULL,
	[UNIT] [VARCHAR](150) NULL,
	[EPIC_DEPARTMENT_ID] [VARCHAR](255) NULL,
	[EPIC_DEPARTMENT_NAME] [VARCHAR](255) NULL,
	[AGE_STATUS] [VARCHAR](150) NULL,
	[DOMAIN] [VARCHAR](150) NULL,
	[GOAL] [DECIMAL](4, 3) NULL,
	[Load_Dtm] [SMALLDATETIME] NULL
) ON [PRIMARY]
GO

GRANT DELETE, INSERT, SELECT, UPDATE ON [Rptg].[ED_Goals] TO [HSCDOM\Decision Support]
GO

INSERT INTO Rptg.ED_Goals
(
    SVC_CDE,
    GOAL_FISCAL_YR,
    SERVICE_LINE,
    UNIT,
    EPIC_DEPARTMENT_ID,
    EPIC_DEPARTMENT_NAME,
    AGE_STATUS,
    DOMAIN,
    GOAL,
    Load_Dtm
)
SELECT SVC_CDE,
       GOAL_FISCAL_YR,
       SERVICE_LINE,
       UNIT,
       EPIC_DEPARTMENT_ID,
       EPIC_DEPARTMENT_NAME,
       AGE_STATUS,
       DOMAIN,
       GOAL,
       Load_Dtm
FROM Rptg.ED_Goals_Test


